{
 "title": "RabbitMQ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections + Channels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "connections" },
    { "expr": "rabbitmq_channels", "legendFormat": "channels" }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "ready" },
    {
     "expr": "rabbitmq_queue_messages_persistent",
     "legendFormat": "persistent"
    },
    {
     "expr": "rabbitmq_queue_messages_unacked",
     "legendFormat": "unacked"
    }
   ]
  },
  {
   "title": "Disk Reds + Writes (per/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queue_disk_reads_total[$__rate_interval]))    ",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(rabbitmq_queue_disk_writes_total[$__rate_interval]))    ",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_process_resident_memory_bytes",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_disk_space_available_bytes",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queue Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ram_bytes",
     "legendFormat": "messages_ram"
    },
    {
     "expr": "rabbitmq_queue_messages_paged_out_bytes",
     "legendFormat": "messages_paged_out"
    },
    {
     "expr": "rabbitmq_queue_process_memory_bytes",
     "legendFormat": "process_memory"
    }
   ]
  },
  {
   "title": "Incoming + Outgoing (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connection_incoming_bytes_total[$__rate_interval]))   ",
     "legendFormat": "incoming"
    },
    {
     "expr": "sum(rate(rabbitmq_connection_outgoing_bytes_total[$__rate_interval]))   ",
     "legendFormat": "outgoing"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk Usage %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (\n    rabbitmq_disk_space_available_bytes / (rabbitmq_disk_space_available_limit_bytes + rabbitmq_disk_space_available_bytes)\n)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}