{
 "title": "Redis",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "connections" }
   ]
  },
  {
   "title": "Stream Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_stream_length", "legendFormat": "size" }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "used" },
    {
     "expr": "redis_total_system_memory_bytes",
     "legendFormat": "total"
    }
   ]
  }
 ]
}